name: Build
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build alpine version
              run: |
                docker build . --file Dockerfile --target build_alpine --tag build_alpine
                docker run -d --rm --name build build_alpine:latest /bin/sleep 60
                docker cp build:/build/target/release/cmdr cmdr-x86_64-alpine
                docker stop -t 1 build

            - name: Upload files to a GitHub release
              uses: svenstaro/upload-release-action@1.0.1
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: cmdr-x86_64-alpine
                asset_name: cmdr-x86_64-alpine
                tag: ${{ github.ref }}
                overwrite: true
